source 'https://rubygems.org'

# Google Cloud DocumentAI (オプショナル)
gem 'google-cloud-document_ai', '~> 2.0', require: false

# EXIF情報読み取り (オプショナル)
gem 'exifr', '~> 1.3', require: false

# JSON処理
gem 'json'

# ファイル操作
gem 'pathname'

# デバッグ用
gem 'pry', group: :development

group :test do
  gem 'rspec', '~> 3.0'
  gem 'rspec-mocks'
end
